# Generated by Django 3.0.7 on 2022-04-20 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20220420_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='photo',
            field=models.ImageField(upload_to='image/%Y/%m/%d/'),
        ),
    ]
