# Generated by Django 3.0.7 on 2022-05-06 15:14

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car_model',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 6, 20, 44, 36, 531456)),
        ),
        migrations.AlterField(
            model_name='car_model',
            name='description',
            field=ckeditor.fields.RichTextField(max_length=500),
        ),
    ]
