# Generated by Django 4.1.3 on 2022-11-22 18:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_auto_20220506_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car_model',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 22, 18, 21, 55, 989506)),
        ),
    ]
