# Generated by Django 3.2.16 on 2022-11-28 15:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_alter_car_model_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car_model',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 28, 20, 55, 38, 321449)),
        ),
    ]
