# Generated by Django 3.2.16 on 2022-12-10 10:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_alter_car_model_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car_model',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 10, 16, 17, 19, 95113)),
        ),
    ]
